config/routes.rb
Rails.application.routes.draw do

  get 'files/index'

  get 'files/new'

  get 'files/create'

  get 'files/destroy'

  devise_for :users
  resources :homes
  
  resources :projects do
    resources :discussions
  end

  resources :projects do
    resources :tasks
  end

  resources :discussions do
    resources :comments
  end

  resources :comments, only: [] do
    resources :likes
  end

  root "homes#index"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :discussion
  belongs_to :user
  has_many :likes, dependent: :nullify
  has_many :users, through: :likes

end

app/models/discussion.rb
class Discussion < ActiveRecord::Base
  belongs_to :project
  has_many :comments, dependent: :destroy
  
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :comment
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :discussions, dependent: :destroy
  has_many :tasks, dependent: :destroy

  validates :title, presence: true
  validates :description, presence: true
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :likes, dependent: :nullify
  has_many :liked_comments, through: :likes, source: :comment

  def has_liked?(comment)
    liked_comments.include? comment
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @discussion = Discussion.find(params[:discussion_id])
    @comment = Comment.new
  end

  def create
    @discussion = Discussion.find(params[:discussion_id])
    @comment = @discussion.comments.build(comment_params)
    @comment.user = current_user
    if @comment.save

      Usermailer.commentcreated_email(@comment).deliver
      redirect_to new_discussion_comment_path(@discussion)
    end
  end



  def edit
    @discussion = Discussion.find(params[:discussion_id])
    @comment = @discussion.comments.find(params[:id])
  end

  def update 
    @discussion = Discussion.find(params[:discussion_id])
    @comment = @discussion.comments.find(params[:id])
    if @comment.update_attributes(comment_params)
      redirect_to new_discussion_comment_path
    else
      render "edit"
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to new_discussion_comment_path
  end

  private
  def comment_params
    params.require(:comment).permit(:id, :description)
  end

end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController

  before_action :find_project, except: [:destroy]

  def new
    @discussion = Discussion.new
  end

  def create
    @discussion = @project.discussions.build(discussion_params)
    if @discussion.save
      redirect_to new_project_discussion_path(@project)
    end
  end

  def edit
    @discussion = @project.discussions.find(params[:id])
  end

  def update
    @discussion = @project.discussions.find(params[:id])
    if @discussion.update_attributes(discussion_params)
      redirect_to new_project_discussion_path
    else
      render "edit"
    end
  end

  def destroy
    @discussion = Discussion.find(params[:id])
    @discussion.destroy
    redirect_to projects_path
  end


  private

  def discussion_params
    params.require(:discussion).permit(:title, :description)
  end

  def find_project
    @project = Project.find(params[:project_id])
  end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def index
  end

  def show
  end


end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  
  def create
    comment  = Comment.find params[:comment_id]
    like      = comment.likes.new
    like.user = current_user
    if like.save
      redirect_to new_discussion_comment_path(comment.discussion), notice: "Liked!"
    else
      redirect_to new_discussion_comment_path(comment.discussion), alert: "Liked Already!"
    end
  end

  def destroy
    comment = Comment.find params[:comment_id]
    like    = comment.likes.find params[:id]
    if like.destroy
      redirect_to new_discussion_comment_path(comment.discussion), notice: "UnLiked!"
    else
      redirect_to new_discussion_comment_path(comment.discussion), alert: "Can't UnLike!"
    end
  end


end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @projects = Project.all
  end

  def show
    

  end

  def new
    @projects = Project.new

  end

  def create #no view
    @projects = Project.new(project_params)
    uploaded_io = params[:project][:doc]
    if @projects.save
      redirect_to projects_path, :notice => "Your project was sent!"
    else 
      render "new"
    end
  end
    
  def edit
    @projects = Project.find(params[:id])
  end

  def update #no view
    @projects = Project.find(params[:id])

    if @projects.update_attributes(project_params)
      redirect_to projects_path, :notice => "Your project has been updated."
    else
      render "edit"
    end
  end

  def destroy #no view
    @projects = Project.find(params[:id])
    @projects.destroy
    redirect_to projects_path, :notice => "Your project has been deleted."
  end

  private
  def project_params
    params.require(:project).permit(:title, :description)
  end


end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def new
    @project = Project.find(params[:project_id])
    @task = Task.new
  end


  def create
    @project = Project.find(params[:project_id])
    @task = @project.tasks.build(task_params)
    if @task.save
      redirect_to new_project_task_path(@project)
    end
  end


  def edit
    @project = Project.find(params[:project_id])
    @task = @project.tasks.find(params[:id])
  end

  def update
    @project = Project.find(params[:project_id])
    @task = @project.tasks.find(params[:id])
    if @task.update_attributes(task_params)
      redirect_to new_project_task_path
    else
      render "edit"
    end
  end


def task_params
    params.require(:task).permit(:id, :description, :title)
  end




end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/discussions_helper.rb
module DiscussionsHelper
end

app/helpers/files_helper.rb
module FilesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/comments/_form.html.erb
<%= form_for [@discussion, @comment] do |f| %>

  <div class="container">
    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_area :description, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.submit "Submit comment", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/comments/edit.html.erb
<%= render "form" %>

app/views/comments/new.html.erb
<script src="http://code.jquery.com/ui/1.11.2/jquery-ui.js"></script>

  <script>
    $(document).ready(function() {
      $('.move').sortable();
      });
  </script>


<div class="container">
  <div class="page-header">
    <h1>Comments<small> Create a comment.</small></h1>
  </div>
</div>

Discussion: <%= @discussion.title %> <%= link_to "Go back?", projects_path %>





<%= render "form" %>

<div class="move">
<% if !@discussion.project.blank? %>
  <% for item in @discussion.comments %>
  <div class="container">
  <div class="panel panel-default">
  <div class="panel-heading">
    <%= item.description %>
    <p>
      <%= link_to "Edit", edit_discussion_comment_path(@discussion, item) %> 
    </p>
      <% if user_signed_in? && current_user.has_liked?(item) %>
        <% like = current_user.likes.find_by_comment_id(item.id) %>
        <%= link_to "unlike", comment_like_path(item, like), class: "btn btn-danger like  ", method: :delete %>
      <% else %>
        <%= link_to "like", comment_likes_path(item), class: "btn btn-info like ", method: :post %>
      <% end %>
    </div>
  </div>
  </div>
  </div>
  <% end %>
<% end %>

app/views/discussions/_form.html.erb
<%= form_for [@project, @discussion] do |f| %>

  <div class="container">

    Project: <%= @project.title %> <%= link_to "Go back?", projects_path %> 
    <hr>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_area :description, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.submit "Submit discussion", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/discussions/new.html.erb
<div class="container">
  <div class="page-header">
    <h1>Discussions<small> Discuss the project.</small></h1>
  </div>
</div>


<%= render "form" %>


<% if !@project.discussions.blank? %>
  <% for item in @project.discussions %>
  <div class="container">
  <div class="panel panel-default">
  <div class="panel-heading">
    <%= item.title %>
  </div>
  </div>
  <div class="panel-body">
  <p>
    <%= item.description %> <br>
    <%= link_to "Comment", new_discussion_comment_path(item) %> |
    <%= link_to "Delete", item, :method => :delete %> |
    <%= link_to "Edit", edit_project_discussion_path(@project, item) %> 
  </p>
  </div>
  </div>
  <% end %>
<% end %>

app/views/files/create.html.erb
<h1>Files#create</h1>
<p>Find me in app/views/files/create.html.erb</p>

app/views/files/destroy.html.erb
<h1>Files#destroy</h1>
<p>Find me in app/views/files/destroy.html.erb</p>

app/views/files/index.html.erb
<h1>Files#index</h1>
<p>Find me in app/views/files/index.html.erb</p>

app/views/files/new.html.erb
<h1>Files#new</h1>
<p>Find me in app/views/files/new.html.erb</p>

app/views/homes/index.html.erb
  <style>

    html, body {
      height: 100%;

    }

    .body {
      background-image: url('/assets/background.jpg');
      height: 100%;
      width: 100%;
      background-size: cover;
    }


    .jumbotron {
      opacity: 0.4;
    }

  </style>

  <div class="body">
    <div class="container">
       <div class="jumbotron">
          <h1>Project Manager</h1>
          <p>Simple project managment tool.</p>
          <p><a class="btn btn-primary btn-lg" href="/projects" role="button">Projects</a></p>
        </div>
      </div>
  </div>

app/views/homes/show.html.erb
<div class="container">
  <div class="page-header">
    <h1>About<small> & FAQ.</small></h1>
  </div>
</div>





<blockquote>
<p>Welcome to our project managment tool. You will be able to create new projects and assign them tasks which you will be able to prioritize! You will also be able to have discussions for each individual project and comment on each individual discussion! How amazing!</p>
</blockquote>

<div class="panel panel-default">
  <div class="panel-body">
    FAQ: What is a FAQ?
  </div>
  <div class="panel-footer">FAQ stands for frequently asked questions.</div>
</div>

<div class="panel panel-default">
  <div class="panel-body">
    FAQ: What is the site for? 
  </div>
  <div class="panel-footer">You will see!</div>
</div>

<div class="panel panel-default">
  <div class="panel-body">
  FAQ: Who is this site meant for? 
  </div>
  <div class="panel-footer">Everybody. Or nobody... I forget.</div>
</div>

<div class="panel panel-default">
  <div class="panel-body">
    FAQ: Interesting...
  </div>
  <div class="panel-footer">Is it..?</div>
</div>

<div class="panel panel-default">
  <div class="panel-body">
    FAQ: Hey, whose the one asking the questions here?
  </div>
  <div class="panel-footer">Technically nobody.</div>
</div>

app/views/projects/_form.html.erb
<%= form_for(@projects, :html => { :multipart => true}) do |f| %>

  <% if @projects.errors.any? %>
    <ul>
      <% @projects.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>



  <div class="container">
    <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
    </div>

    <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control" %>
    </div>
 
    <%= label_tag :doc, 'Files (optional)' %>
    <%= file_field_tag :doc %>

    <br>

    <div class="form-group">
    <%= f.submit "Submit Project", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<div class="container">
  <div class="page-header">
    <h1>Projects<small> Edit your project.</small></h1>
  </div>
</div>


<%= render "form" %>

app/views/projects/index.html.erb
<div class="container">
  <div class="page-header">
    <h1>Projects<small> Here are all of your projects.</small></h1>
  </div>
</div>

<% @projects.each do |project| %>
<div class="panel panel-default">
<div class="panel-heading">
<%= project.title %>
</div>
</div>
<div class="panel-body">
<p>
<%= project.description %> 
</p>
<br>
<%= link_to "Discuss", new_project_discussion_path(project) %> |
<%= link_to "Tasks", new_project_task_path(project) %> |
<%= link_to "Edit", edit_project_path(project) %> |
<%= link_to "Delete", project, :method => :delete %> 

<% if project.doc %>
  <p>Document: <%= link_to project.doc.original_filename, "/uploads/#{@project.doc}", :target => "_blank" %></p>
<% end %>


</div>
</div>
<%end%>

<br>
<br>

<div class="container">
  <p><a class="btn btn-primary btn-lg" href="/projects/new" role="button">Create project</a></p>
</div>

app/views/projects/new.html.erb
<div class="container">
  <div class="page-header">
    <h1>Projects<small> Submit a new project.</small></h1>
  </div>
</div>


<%= render "form" %>

app/views/tasks/_form.html.erb
<%= form_for [@project, @task] do |f| %>
  <div class="container">
    <hr>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_area :description, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.submit "Submit Task", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<%= render "form" %>

app/views/tasks/new.html.erb
<script src="http://code.jquery.com/ui/1.11.2/jquery-ui.js"></script>

<div class="container">
  <div class="page-header">
    <h1>Tasks<small> Here are all of your tasks.</small></h1>
  </div>
  <p>Drag and drop each task to prioritize them. To reset the tasks to their original order just refresh the page! (It's a feature not a bug, of course)</p>
</div>

  <script>
    $(document).ready(function() {
      $('.move').sortable();
      });


    $("div").click(function(){
    var index = $("div").index($(this));
    var position =  index+1;
    $('span').html(position);
})
  </script>


<%= render "form" %>




<div class="move">
<% if !@project.tasks.blank? %>
  <% for item in @project.tasks %>
  <div class="container">
  <div class="panel panel-default">
  <div class="panel-heading">
    <div class='move'><%= item.title %></div>
  </div>
  </div>
  <div class="panel-body">
  <p>
    <div class='move'><%= item.description %></div>
  </p>
  <%= link_to "Edit", edit_project_task_path(@project, item) %> 
  </div>
  </div>
  <% end %>
<% end %>
</div>